language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
dist: precise
sudo: false

before_script:
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit